<a href="https://colab.research.google.com/github/DatascienceSandra/codespaces-jupyter/blob/main/Pandas_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
import pandas as pd

# Define a sample DataFrame
data = {
    'job_title': ['Data Analyst', 'Data Engineer', 'Data Scientist'],
    'salary': [60000, 80000, 90000]
}
df = pd.DataFrame(data)

# Display DataFrame information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   job_title  3 non-null      object
 1   salary     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [6]:
df.describe

<bound method NDFrame.describe of         job_title  salary
0    Data Analyst   60000
1   Data Engineer   80000
2  Data Scientist   90000>

In [8]:
import pandas as pd

# Example DataFrame
data = {
    'job_title': ['Data Analyst', 'Business Analyst', 'Data Engineer', 'Data Scientist']
}
df = pd.DataFrame(data)

# Check column names
print("Column names:", df.columns)

# Access the unique values
unique_titles = df['job_title'].unique()  # Use the correct column name
print(unique_titles)

Column names: Index(['job_title'], dtype='object')
['Data Analyst' 'Business Analyst' 'Data Engineer' 'Data Scientist']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   job_title  4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes

In [11]:
# Check column names
print("Columns in DataFrame:", df.columns)

# Use bracket notation to access column
if 'job_posted_date' in df.columns:
    print(type(df['job_posted_date'][0]))  # Display the type of the first value
else:
    print("'job_posted_date' column is missing!")

Columns in DataFrame: Index(['job_title'], dtype='object')
'job_posted_date' column is missing!

In [13]:
import pandas as pd

# Sample DataFrame
data = {'job_posted_date': ['2024-01-15', '2024-02-20', '2024-03-10']}
df = pd.DataFrame(data)

# Convert job_posted_date to datetime
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce')

# Extract the month
df['job_posted_month'] = df['job_posted_date'].dt.month

print(df)

  job_posted_date  job_posted_month
0      2024-01-15                 1
1      2024-02-20                 2
2      2024-03-10                 3

In [15]:
df.sort_values(by='job_posted_date', inplace=True)

In [16]:
df

  job_posted_date  job_posted_month
0      2024-01-15                 1
1      2024-02-20                 2
2      2024-03-10                 3

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_posted_date   3 non-null      datetime64[ns]
 1   job_posted_month  3 non-null      int32
dtypes: datetime64[ns](1), int32(1)
memory usage: 164.0 bytes

In [18]:
# Check and drop the column if it exists
if 'salary_hour_avg' in df.columns:
    df.drop(labels='salary_hour_avg', axis=1, inplace=True)
else:
    print("'salary_hour_avg' column not found.")

'salary_hour_avg' column not found.

In [21]:
df.count()

job_posted_date     3
job_posted_month    3
dtype: int64

In [22]:
df.median()

job_posted_date     2024-02-20 00:00:00
job_posted_month                    2.0
dtype: object

In [25]:
# Verify all column names
print("Available columns:", df.columns)

# Check if the column exists before accessing it
if 'salary_year_avg' in df.columns:
    print(df['salary_year_avg'])
else:
    print("'salary_year_avg' column not found.")

Available columns: Index(['job_posted_date', 'job_posted_month'], dtype='object')
'salary_year_avg' column not found.

In [27]:
# Check column names
print("Columns in the DataFrame:", df.columns)

# Access column if it exists
if 'job_title_short' in df.columns:
    print(df['job_title_short'])
else:
    print("'job_title_short' column not found.")

Columns in the DataFrame: Index(['job_posted_date', 'job_posted_month'], dtype='object')
'job_title_short' column not found.

In [29]:
# Check and print column
if 'job_title_short' in df.columns:
    print(df['job_title_short'].unique())
else:
    print("'job_title_short' column not found.")

'job_title_short' column not found.

In [31]:
# Step 1: Check if 'job_title_short' exists
if 'job_title_short' not in df.columns:
    if 'job_title' in df.columns:
        # Create 'job_title_short' if derivable
        df['job_title_short'] = df['job_title'].str.split().str[0]
        print("'job_title_short' column created successfully.")
    else:
        print("'job_title_short' and 'job_title' columns are missing.")
        # Exit early if necessary
        exit()

# Step 2: Group and aggregate
try:
    result = df.groupby('job_title_short')['job_title_short'].min()
    print(result)
except KeyError as e:
    print(f"KeyError: {e}")

'job_title_short' and 'job_title' columns are missing.
KeyError: 'job_title_short'

In [4]:
import pandas as pd

# Example data
data = {
    'job_country': ['United States', 'Canada', 'United States', 'Germany'],
    'job_title': ['Data Analyst', 'Data Scientist', 'Business Analyst', 'Engineer']
}
df = pd.DataFrame(data)

In [5]:
df

     job_country         job_title
0  United States      Data Analyst
1         Canada    Data Scientist
2  United States  Business Analyst
3        Germany          Engineer

In [24]:
# ... (previous code)

# Apply aggregation to numeric columns
agg_result = numeric_columns.agg(['median', 'min', 'max', 'count'])

# **Modification:** Reset the index and flatten multi-level columns
agg_result.columns = ['_'.join(col).strip() for col in agg_result.columns.values]
agg_result = agg_result.reset_index()

# Sort by the relevant median column (e.g., 'salary_year_avg_median')
# Make sure to adjust 'salary_year_avg_median' if your numeric column is different
if 'salary_year_avg_median' in agg_result.columns:
    sorted_result = agg_result.sort_values(by='salary_year_avg_median', ascending=False)
else:
    print("The aggregated median column (e.g., 'salary_year_avg_median') is not found. Please check your numeric columns.")
    # Handle the case where the expected median column is not present

# Display the result

The aggregated median column (e.g., 'salary_year_avg_median') is not found. Please check your numeric columns.